export enum EStatus {
  CREATED = 'CREATED',
  WAITING_APPROVAL = 'WAITING_APPROVAL',
  IN_REPAIR = 'IN_REPAIR',
  ACTIVE = 'ACTIVE',
  UPDATED = 'UPDATED',
  BLOCKED = 'BLOCKED',
  REMOVED = 'REMOVED',
  DELETED = 'DELETED',

  // statuses for Account model:
  OPEN = 'OPEN',
  BLOCKED_CREDIT = 'BLOCKED_CREDIT',
  BLOCKED_DEBIT = 'BLOCKED_DEBIT',
  CLOSED = 'CLOSED',
}
